from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.challenge import (
    Challenge,
    ChallengeStatus,
)
from app.models.user import User
from app.schemas.challenge import ChallengeCreate, ChallengeUpdate

from typing import Any


def create_challenge(
    db: Session,
    challenge_data: ChallengeCreate,
    current_user: User,
) -> Challenge:
    challenge = Challenge(
        title=challenge_data.title,
        description=challenge_data.description,
        submitted_by=current_user.id,
        category=challenge_data.category,
        urgency=challenge_data.urgency,
        affected_population=challenge_data.affected_population,
        estimated_economic_loss=challenge_data.estimated_economic_loss,
        address=challenge_data.address,
        district=challenge_data.district,
        state=challenge_data.state,
        latitude=challenge_data.latitude,
        longitude=challenge_data.longitude,
    )

    db.add(challenge)
    db.commit()
    db.refresh(challenge)

    return challenge


def get_challenge_by_id(
    db: Session,
    challenge_id: int,
) -> Challenge | None:
    statement = select(Challenge).where(
        Challenge.id == challenge_id
    )
    return db.scalar(statement)


def get_challenges(
    db: Session,
    skip: int = 0,
    limit: int = 20,
) -> list[Challenge]:
    statement = (
        select(Challenge)
        .order_by(Challenge.created_at.desc())
        .offset(skip)
        .limit(limit)
    )

    return list(db.scalars(statement).all())


def get_user_challenges(
    db: Session,
    user_id: int,
    skip: int = 0,
    limit: int = 20,
) -> list[Challenge]:
    statement = (
        select(Challenge)
        .where(Challenge.submitted_by == user_id)
        .order_by(Challenge.created_at.desc())
        .offset(skip)
        .limit(limit)
    )

    return list(db.scalars(statement).all())


def update_challenge(
    db: Session,
    challenge: Challenge,
    challenge_data: ChallengeUpdate,
) -> Challenge:
    update_data = challenge_data.model_dump(
        exclude_unset=True
    )

    for field, value in update_data.items():
        setattr(challenge, field, value)

    db.commit()
    db.refresh(challenge)

    return challenge

def _json_safe(value: Any):
    """
    Convert Pydantic models and nested structures into
    JSON-serializable Python primitives.
    """
    if value is None:
        return None

    if hasattr(value, "model_dump"):
        return value.model_dump()

    if hasattr(value, "dict"):
        return value.dict()

    if isinstance(value, list):
        return [_json_safe(item) for item in value]

    if isinstance(value, tuple):
        return [_json_safe(item) for item in value]

    if isinstance(value, dict):
        return {
            key: _json_safe(val)
            for key, val in value.items()
        }

    return value

def persist_ai_triage_result(
    db: Session,
    challenge: Challenge,
    triage_result,
) -> Challenge:
    """
    Persist the AI triage result generated by triage_service.py.

    Existing fields remain the canonical challenge-routing fields.
    Additional AI fields preserve model evidence for explainability,
    auditability, and frontend display.
    """

    challenge.category = triage_result.category
    challenge.severity = triage_result.severity
    challenge.urgency = triage_result.urgency
    challenge.innovation_required = (
        triage_result.innovation_required
    )

    challenge.ai_confidence_score = (
        triage_result.category_confidence
    )
    challenge.ai_model_version = (
        triage_result.model_version
    )

    challenge.ai_category_confidence = (
        triage_result.category_confidence
    )
    challenge.ai_second_category = (
        triage_result.second_category
    )
    challenge.ai_second_category_confidence = (
        triage_result.second_category_confidence
    )
    challenge.ai_category_margin = (
        triage_result.category_margin
    )
    challenge.ai_category_decision = (
        triage_result.category_decision
    )
    challenge.ai_requires_human_review = (
        triage_result.requires_human_review
    )
    challenge.ai_category_top_3 = _json_safe(
        triage_result.category_top_3
    )
    challenge.ai_analysis_at = (
        datetime.now(timezone.utc)
    )

    challenge.routing_type = (
        triage_result.routing_type
    )
    challenge.routing_reason = (
        triage_result.routing_reason
    )

    if triage_result.requires_human_review:
        challenge.status = ChallengeStatus.UNDER_REVIEW
    else:
        challenge.status = ChallengeStatus.ROUTED

    db.commit()
    db.refresh(challenge)

    return challenge
