"""add is_anonymous and upvotes to challenges

Revision ID: 70d70087646b
Revises: 735717c758fc
Create Date: 2026-09-17 08:39:33.487265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d70087646b'
down_revision: Union[str, Sequence[str], None] = '735717c758fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.add_column('challenges', sa.Column('upvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'upvotes')
    op.drop_column('challenges', 'is_anonymous')
    # ### end Alembic commands ###
