"""add authority hierarchy and challenge assignment workflow

Revision ID: eeb2ef8c4a89
Revises: e78b8cbe303c
Create Date: 2026-09-11 22:51:36.101602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb2ef8c4a89'
down_revision: Union[str, Sequence[str], None] = 'e78b8cbe303c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('from_authority_id', sa.Integer(), nullable=True),
    sa.Column('to_authority_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('AUTO_ASSIGNED', 'HUMAN_ASSIGNED', 'REASSIGNED', 'ESCALATED', 'DELEGATED_DOWN', 'SENT_TO_INNOVATION', name='assignmentaction'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_authority_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_authority_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_assignments_action'), 'challenge_assignments', ['action'], unique=False)
    op.create_index(op.f('ix_challenge_assignments_challenge_id'), 'challenge_assignments', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_assignments_from_authority_id'), 'challenge_assignments', ['from_authority_id'], unique=False)
    op.create_index(op.f('ix_challenge_assignments_performed_by'), 'challenge_assignments', ['performed_by'], unique=False)
    op.create_index(op.f('ix_challenge_assignments_status'), 'challenge_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_challenge_assignments_to_authority_id'), 'challenge_assignments', ['to_authority_id'], unique=False)
    op.add_column('challenges', sa.Column('current_authority_id', sa.Integer(), nullable=True))
    op.add_column('challenges', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('challenges', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_challenges_assigned_by'), 'challenges', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_challenges_current_authority_id'), 'challenges', ['current_authority_id'], unique=False)
    op.create_foreign_key(None, 'challenges', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'challenges', 'organizations', ['current_authority_id'], ['id'], ondelete='SET NULL')
    op.add_column('organizations', sa.Column('parent_organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organizations_parent_organization_id'), 'organizations', ['parent_organization_id'], unique=False)
    op.create_foreign_key(None, 'organizations', 'organizations', ['parent_organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_parent_organization_id'), table_name='organizations')
    op.drop_column('organizations', 'parent_organization_id')
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_current_authority_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_assigned_by'), table_name='challenges')
    op.drop_column('challenges', 'assigned_by')
    op.drop_column('challenges', 'assigned_at')
    op.drop_column('challenges', 'current_authority_id')
    op.drop_index(op.f('ix_challenge_assignments_to_authority_id'), table_name='challenge_assignments')
    op.drop_index(op.f('ix_challenge_assignments_status'), table_name='challenge_assignments')
    op.drop_index(op.f('ix_challenge_assignments_performed_by'), table_name='challenge_assignments')
    op.drop_index(op.f('ix_challenge_assignments_from_authority_id'), table_name='challenge_assignments')
    op.drop_index(op.f('ix_challenge_assignments_challenge_id'), table_name='challenge_assignments')
    op.drop_index(op.f('ix_challenge_assignments_action'), table_name='challenge_assignments')
    op.drop_table('challenge_assignments')
    # ### end Alembic commands ###
