"""initial schema

Revision ID: 02ac3e7aa484
Revises: 
Create Date: 2026-09-08 01:21:23.443617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ac3e7aa484'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.Enum('MUNICIPALITY', 'GOVERNMENT_DEPARTMENT', 'UNIVERSITY', 'INDUSTRY', name='organizationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_district'), 'organizations', ['district'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_organization_type'), 'organizations', ['organization_type'], unique=False)
    op.create_index(op.f('ix_organizations_state'), 'organizations', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CITIZEN', 'MUNICIPALITY_OFFICER', 'GOVERNMENT_OFFICER', 'UNIVERSITY_ADMIN', 'FACULTY', 'STUDENT', 'INDUSTRY_ADMIN', 'INDUSTRY_MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('WATER', 'SANITATION', 'WASTE_MANAGEMENT', 'HEALTHCARE', 'EDUCATION', 'AGRICULTURE', 'TRANSPORTATION', 'ENERGY', 'ENVIRONMENT', 'PUBLIC_SAFETY', 'INFRASTRUCTURE', 'DIGITAL_SERVICES', 'EMPLOYMENT', 'SOCIAL_WELFARE', 'DISASTER_MANAGEMENT', 'OTHER', name='challengecategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='challengeseverity'), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='challengeurgency'), nullable=False),
    sa.Column('affected_population', sa.Integer(), nullable=True),
    sa.Column('estimated_economic_loss', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('innovation_required', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('routing_type', sa.Enum('MUNICIPALITY', 'GOVERNMENT', 'INNOVATION', 'HUMAN_REVIEW', name='challengeroutingtype'), nullable=False),
    sa.Column('routing_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_AI_ANALYSIS', 'UNDER_REVIEW', 'ROUTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'CLOSED', name='challengestatus'), nullable=False),
    sa.Column('is_master_challenge', sa.Boolean(), nullable=False),
    sa.Column('master_challenge_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_category'), 'challenges', ['category'], unique=False)
    op.create_index(op.f('ix_challenges_district'), 'challenges', ['district'], unique=False)
    op.create_index(op.f('ix_challenges_innovation_required'), 'challenges', ['innovation_required'], unique=False)
    op.create_index(op.f('ix_challenges_master_challenge_id'), 'challenges', ['master_challenge_id'], unique=False)
    op.create_index(op.f('ix_challenges_routing_type'), 'challenges', ['routing_type'], unique=False)
    op.create_index(op.f('ix_challenges_severity'), 'challenges', ['severity'], unique=False)
    op.create_index(op.f('ix_challenges_state'), 'challenges', ['state'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_submitted_by'), 'challenges', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_index(op.f('ix_challenges_urgency'), 'challenges', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_urgency'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_submitted_by'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_state'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_severity'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_routing_type'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_master_challenge_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_innovation_required'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_district'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_category'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_state'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_organization_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_district'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
