"""add challenge evidence

Revision ID: 10cd682a5f5b
Revises: 6ec63aa64283
Create Date: 2026-09-08 01:44:20.828517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cd682a5f5b'
down_revision: Union[str, Sequence[str], None] = '6ec63aa64283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'OTHER', name='evidencetype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_challenge_evidence_challenge_id'), 'challenge_evidence', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_evidence_evidence_type'), 'challenge_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_challenge_evidence_uploaded_by'), 'challenge_evidence', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_evidence_uploaded_by'), table_name='challenge_evidence')
    op.drop_index(op.f('ix_challenge_evidence_evidence_type'), table_name='challenge_evidence')
    op.drop_index(op.f('ix_challenge_evidence_challenge_id'), table_name='challenge_evidence')
    op.drop_table('challenge_evidence')
    # ### end Alembic commands ###
