"""persist ai triage analysis

Revision ID: 5d57c7b44218
Revises: e59850d273b4
Create Date: 2026-09-09 00:44:39.820989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d57c7b44218'
down_revision: Union[str, Sequence[str], None] = 'e59850d273b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('ai_category_confidence', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_second_category', sa.String(length=100), nullable=True))
    op.add_column('challenges', sa.Column('ai_second_category_confidence', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_category_margin', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_category_decision', sa.String(length=50), nullable=True))
    op.add_column('challenges', sa.Column('ai_requires_human_review', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('ai_category_top_3', sa.JSON(), nullable=True))
    op.add_column('challenges', sa.Column('ai_analysis_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'ai_analysis_at')
    op.drop_column('challenges', 'ai_category_top_3')
    op.drop_column('challenges', 'ai_requires_human_review')
    op.drop_column('challenges', 'ai_category_decision')
    op.drop_column('challenges', 'ai_category_margin')
    op.drop_column('challenges', 'ai_second_category_confidence')
    op.drop_column('challenges', 'ai_second_category')
    op.drop_column('challenges', 'ai_category_confidence')
    # ### end Alembic commands ###
