"""add innovation ai assessment fields

Revision ID: 942a100aab4a
Revises: 5d57c7b44218
Create Date: 2026-09-10 14:49:12.673606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942a100aab4a'
down_revision: Union[str, Sequence[str], None] = '5d57c7b44218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('ai_innovation_confidence', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_decision', sa.String(length=50), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_requires_human_review', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type', sa.String(length=100), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_confidence', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_second', sa.String(length=100), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_second_confidence', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_margin', sa.Float(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_decision', sa.String(length=50), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_requires_human_review', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('ai_innovation_type_top_3', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'ai_innovation_type_top_3')
    op.drop_column('challenges', 'ai_innovation_type_requires_human_review')
    op.drop_column('challenges', 'ai_innovation_type_decision')
    op.drop_column('challenges', 'ai_innovation_type_margin')
    op.drop_column('challenges', 'ai_innovation_type_second_confidence')
    op.drop_column('challenges', 'ai_innovation_type_second')
    op.drop_column('challenges', 'ai_innovation_type_confidence')
    op.drop_column('challenges', 'ai_innovation_type')
    op.drop_column('challenges', 'ai_innovation_requires_human_review')
    op.drop_column('challenges', 'ai_innovation_decision')
    op.drop_column('challenges', 'ai_innovation_confidence')
    # ### end Alembic commands ###
