"""increase ai model version length

Revision ID: c87190ea90f4
Revises: 648027520099
Create Date: 2026-09-11 00:39:02.878592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87190ea90f4'
down_revision: Union[str, Sequence[str], None] = '648027520099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'ai_model_version',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=225),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'ai_model_version',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
