"""update challenge model

Revision ID: e59850d273b4
Revises: 10cd682a5f5b
Create Date: 2026-09-08 02:28:35.016677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e59850d273b4'
down_revision: Union[str, Sequence[str], None] = '10cd682a5f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('challenge_evidence_uploaded_by_fkey'), 'challenge_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'challenge_evidence', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('challenges', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('challenges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('challenges', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'challenge_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('challenge_evidence_uploaded_by_fkey'), 'challenge_evidence', 'users', ['uploaded_by'], ['id'])
    op.alter_column('challenge_evidence', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
